"""erp_expansion

Revision ID: d6e7b1599853
Revises: 0013
Create Date: 2026-05-12 18:14:20.185288
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd6e7b1599853'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_phone'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_timestamp'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_admin_logs_level'), table_name='admin_logs')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.drop_column('contacts', 'landline')
    op.drop_column('contacts', 'mobile')
    op.drop_column('contacts', 'notification_prefs')
    op.drop_column('contacts', 'company')
    op.add_column('elevators', sa.Column('installation_status', sa.String(length=50), nullable=True))
    op.add_column('elevators', sa.Column('handover_date', sa.Date(), nullable=True))
    op.add_column('elevators', sa.Column('dismantle_date', sa.Date(), nullable=True))
    op.add_column('elevators', sa.Column('engine_serial', sa.String(length=100), nullable=True))
    op.add_column('elevators', sa.Column('controller_serial', sa.String(length=100), nullable=True))
    op.add_column('elevators', sa.Column('load_capacity_kg', sa.Integer(), nullable=True))
    op.add_column('elevators', sa.Column('max_persons', sa.Integer(), nullable=True))
    op.add_column('elevators', sa.Column('speed_m_s', sa.Float(), nullable=True))
    op.add_column('elevators', sa.Column('stops_count', sa.Integer(), nullable=True))
    op.add_column('elevators', sa.Column('doors_count', sa.Integer(), nullable=True))
    op.add_column('elevators', sa.Column('door_width_cm', sa.Integer(), nullable=True))
    op.add_column('elevators', sa.Column('cabin_finish', sa.String(length=100), nullable=True))
    op.add_column('elevators', sa.Column('floor_type', sa.String(length=100), nullable=True))
    op.add_column('elevators', sa.Column('accessibility_compliant', sa.Boolean(), nullable=False))
    op.add_column('elevators', sa.Column('fire_system_connected', sa.Boolean(), nullable=False))
    op.add_column('elevators', sa.Column('generator_connected', sa.Boolean(), nullable=False))
    op.add_column('elevators', sa.Column('iot_gateway_ip', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('elevators_labor_file_number_key'), 'elevators', type_='unique')
    op.drop_constraint(op.f('elevators_serial_number_key'), 'elevators', type_='unique')
    op.drop_index(op.f('ix_elevators_responsible_technician_id'), table_name='elevators')
    op.create_index(op.f('ix_elevators_building_id'), 'elevators', ['building_id'], unique=False)
    op.create_index(op.f('ix_elevators_internal_number'), 'elevators', ['internal_number'], unique=True)
    op.create_index(op.f('ix_elevators_labor_file_number'), 'elevators', ['labor_file_number'], unique=True)
    op.drop_constraint(op.f('elevators_responsible_technician_id_fkey'), 'elevators', type_='foreignkey')
    op.drop_column('elevators', 'lead_source')
    op.drop_column('elevators', 'responsible_technician_id')
    op.alter_column('inspection_reports', 'deficiencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('inspection_reports', 'match_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'AUTO_MATCHED'::character varying"))
    op.drop_column('inspection_reports', 'model')
    op.drop_column('inspection_reports', 'inspector_phone')
    op.drop_column('inspection_reports', 'floor_count')
    op.drop_column('inspection_reports', 'manufacturer')
    op.drop_column('inspection_reports', 'inspector_mobile')
    op.drop_column('inspection_reports', 'inspector_license')
    op.drop_column('inspection_reports', 'next_inspection_date')
    op.drop_column('inspection_reports', 'inspector_email')
    op.alter_column('management_companies', 'caller_phones',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=app.models.elevator._FlexArray(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('management_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('management_companies_name_key'), 'management_companies', type_='unique')
    op.create_index(op.f('ix_management_companies_name'), 'management_companies', ['name'], unique=True)
    op.add_column('parts', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('parts', sa.Column('manufacturer_part_number', sa.String(length=100), nullable=True))
    op.add_column('parts', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('parts', sa.Column('dimensions', sa.String(length=50), nullable=True))
    op.add_column('parts', sa.Column('storage_slot', sa.String(length=50), nullable=True))
    op.add_column('parts', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('parts', sa.Column('tax_exempt', sa.Boolean(), nullable=False))
    op.add_column('parts', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('parts', sa.Column('last_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('parts', sa.Column('average_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_parts_barcode'), 'parts', ['barcode'], unique=False)
    op.add_column('service_calls', sa.Column('contract_id', sa.Uuid(), nullable=True))
    op.add_column('service_calls', sa.Column('is_chargeable', sa.Boolean(), nullable=False))
    op.add_column('service_calls', sa.Column('invoice_id', sa.Uuid(), nullable=True))
    op.add_column('service_calls', sa.Column('quote_id', sa.Uuid(), nullable=True))
    op.add_column('service_calls', sa.Column('customer_po_number', sa.String(length=50), nullable=True))
    op.add_column('service_calls', sa.Column('technician_arrival_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service_calls', sa.Column('technician_departure_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service_calls', sa.Column('travel_time_minutes', sa.Integer(), nullable=True))
    op.add_column('service_calls', sa.Column('work_time_minutes', sa.Integer(), nullable=True))
    op.add_column('service_calls', sa.Column('requires_time_report', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('service_calls', sa.Column('malfunction_code', sa.String(length=50), nullable=True))
    op.add_column('service_calls', sa.Column('repair_code', sa.String(length=50), nullable=True))
    op.add_column('service_calls', sa.Column('contact_name_on_site', sa.String(length=100), nullable=True))
    op.add_column('service_calls', sa.Column('customer_signature_url', sa.Text(), nullable=True))
    op.drop_index(op.f('uq_service_calls_call_number'), table_name='service_calls', postgresql_where='(call_number IS NOT NULL)')
    op.create_index(op.f('ix_service_calls_contract_id'), 'service_calls', ['contract_id'], unique=False)
    op.drop_constraint(op.f('service_calls_elevator_id_fkey'), 'service_calls', type_='foreignkey')
    op.create_foreign_key(None, 'service_calls', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'service_calls', 'elevators', ['elevator_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'service_calls', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'service_calls', 'quotes', ['quote_id'], ['id'], ondelete='SET NULL')
    op.alter_column('system_settings', 'modules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_column('system_settings', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('system_settings', 'modules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'service_calls', type_='foreignkey')
    op.drop_constraint(None, 'service_calls', type_='foreignkey')
    op.drop_constraint(None, 'service_calls', type_='foreignkey')
    op.drop_constraint(None, 'service_calls', type_='foreignkey')
    op.create_foreign_key(op.f('service_calls_elevator_id_fkey'), 'service_calls', 'elevators', ['elevator_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_calls_contract_id'), table_name='service_calls')
    op.create_index(op.f('uq_service_calls_call_number'), 'service_calls', ['call_number'], unique=True, postgresql_where='(call_number IS NOT NULL)')
    op.drop_column('service_calls', 'customer_signature_url')
    op.drop_column('service_calls', 'contact_name_on_site')
    op.drop_column('service_calls', 'repair_code')
    op.drop_column('service_calls', 'malfunction_code')
    op.drop_column('service_calls', 'requires_time_report')
    op.drop_column('service_calls', 'work_time_minutes')
    op.drop_column('service_calls', 'travel_time_minutes')
    op.drop_column('service_calls', 'technician_departure_time')
    op.drop_column('service_calls', 'technician_arrival_time')
    op.drop_column('service_calls', 'customer_po_number')
    op.drop_column('service_calls', 'quote_id')
    op.drop_column('service_calls', 'invoice_id')
    op.drop_column('service_calls', 'is_chargeable')
    op.drop_column('service_calls', 'contract_id')
    op.drop_index(op.f('ix_parts_barcode'), table_name='parts')
    op.drop_column('parts', 'average_cost')
    op.drop_column('parts', 'last_purchase_price')
    op.drop_column('parts', 'currency')
    op.drop_column('parts', 'tax_exempt')
    op.drop_column('parts', 'lead_time_days')
    op.drop_column('parts', 'storage_slot')
    op.drop_column('parts', 'dimensions')
    op.drop_column('parts', 'weight_kg')
    op.drop_column('parts', 'manufacturer_part_number')
    op.drop_column('parts', 'barcode')
    op.drop_index(op.f('ix_management_companies_name'), table_name='management_companies')
    op.create_unique_constraint(op.f('management_companies_name_key'), 'management_companies', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('management_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('management_companies', 'caller_phones',
               existing_type=app.models.elevator._FlexArray(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.add_column('inspection_reports', sa.Column('inspector_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('next_inspection_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('inspector_license', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('inspector_mobile', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('floor_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('inspector_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('inspection_reports', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('inspection_reports', 'match_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'AUTO_MATCHED'::character varying"))
    op.alter_column('inspection_reports', 'deficiencies',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('elevators', sa.Column('responsible_technician_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('elevators', sa.Column('lead_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('elevators_responsible_technician_id_fkey'), 'elevators', 'technicians', ['responsible_technician_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_elevators_labor_file_number'), table_name='elevators')
    op.drop_index(op.f('ix_elevators_internal_number'), table_name='elevators')
    op.drop_index(op.f('ix_elevators_building_id'), table_name='elevators')
    op.create_index(op.f('ix_elevators_responsible_technician_id'), 'elevators', ['responsible_technician_id'], unique=False)
    op.create_unique_constraint(op.f('elevators_serial_number_key'), 'elevators', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('elevators_labor_file_number_key'), 'elevators', ['labor_file_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('elevators', 'iot_gateway_ip')
    op.drop_column('elevators', 'generator_connected')
    op.drop_column('elevators', 'fire_system_connected')
    op.drop_column('elevators', 'accessibility_compliant')
    op.drop_column('elevators', 'floor_type')
    op.drop_column('elevators', 'cabin_finish')
    op.drop_column('elevators', 'door_width_cm')
    op.drop_column('elevators', 'doors_count')
    op.drop_column('elevators', 'stops_count')
    op.drop_column('elevators', 'speed_m_s')
    op.drop_column('elevators', 'max_persons')
    op.drop_column('elevators', 'load_capacity_kg')
    op.drop_column('elevators', 'controller_serial')
    op.drop_column('elevators', 'engine_serial')
    op.drop_column('elevators', 'dismantle_date')
    op.drop_column('elevators', 'handover_date')
    op.drop_column('elevators', 'installation_status')
    op.add_column('contacts', sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('mobile', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('landline', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_admin_logs_level'), 'admin_logs', ['level'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('msg_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_messages_pkey'))
    )
    op.create_index(op.f('ix_whatsapp_messages_timestamp'), 'whatsapp_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_phone'), 'whatsapp_messages', ['phone'], unique=False)
    # ### end Alembic commands ###
